### ISSUE TITLE
Transpose rule for 'allreduce_mpi' 

### ISSUE THREAD

**Issue by inailuig** [PhilipVinc/mpi4jax#34]
I am trying to use `Allreduce` (with `MPI_SUM`) in a matvec function passed to [`jax.scipy.sparse.linalg.cg`](https://jax.readthedocs.io/en/latest/_autosummary/jax.scipy.sparse.linalg.cg.html#jax.scipy.sparse.linalg.cg), however I get the following error:
```NotImplementedError: Transpose rule (for reverse-mode differentiation) for 'allreduce_mpi' not implemented```

(Internally `cg` uses [`custom_linear_solve`](https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.custom_linear_solve.html) in order to define the gradients of the solver which in turn calls [`linear_transpose`](https://jax.readthedocs.io/en/latest/jax.html#jax.linear_transpose) for matvec)

**Comment by inailuig** [comment]
I was thinking a bit about how the rule would have to look like.
Essentially what the `Allreduce` does is calculate the sum of all elements and then broadcast it to all ranks.

Just considering the sum as a linear operator its matrix is just a row vector of 1s, which when applied (multiplied) to a column vector, say `x`, returns a scalar.
So clearly its transpose is a row vector of 1s, and when that is applied to an element of the dual space (just a scalar) all it does is broadcast that element to a vector which has the shape of `x`. Since that is distributed across the mpi ranks (where each rank contains just one element) the transpose rule can just return the dual argument on each rank. This is exactly what the current jvp rule does, but omitting the forward pass.

Considering the broadcast to all ranks its just a column vector of 1s, so its transpose is a row vector of 1s which is a sum.

When we concatenate both (row vector of 1s times column vector of 1s) the Allreduce is just a square matrix of all 1s, and so its transpose is just another Allreduce. I think this is also what the [transpose rule for psum](https://github.com/google/jax/blob/d8aabdb8c655867933220e36efd531052daa83b8/jax/_src/lax/parallel.py#L464) does.

**Comment by PhilipVinc** [comment]
> Since that is distributed across the mpi ranks (where each rank contains just one element) the transpose rule can just return the dual argument on each rank. 
With dual argument you mean the forward (or input) sensitivity, right? in that case I agree.

>This is exactly what the current jvp rule does, but omitting the forward pass.
Technically what. [`mpi_allreduce_value_and_jvp(in_args, tan_args, op, comm)`](https://github.com/PhilipVinc/mpi4jax/blob/875e60b1737014ecd6885f4c64564705b5ce3c81/mpi4jax/collective_ops/allreduce.py#L157) does is only perform only one forward pass, on the dual number `(in_args, tan_args) -> (Allreduce_value(in_args, tan_args), Allreduce_sensitivity(in_args, tan_args)` where `tan_args` are the sensitivities. But I guess what you mean is that we only want to compute only the output sensitivity.

> Considering the broadcast to all ranks its just a column vector of 1s, so its transpose is a row vector of 1s which is a sum.
yes...

> When we concatenate both (column vector of 1s times row vector of 1s) the Allreduce is just a square matrix of all 1s, and so its transpose is just another Allreduce
I don't follow your argument. Why are we concatenating?

**Comment by inailuig** [comment]
Essentially what I am saying is that the linear operator allreduce and its transpose operators are identical (and also jvp and vjp), and are all represented by a square matrix filled with 1s.

I think its more clear with a code example:

```
import jax

x = jax.numpy.array([1.,2.,3.])
y = jax.numpy.array([5.,6.,7.])

def _sum(x):
    return jax.lax.dot(jax.numpy.ones(3), x)

def _broadcast(y):
    return jax.lax.broadcast(y,(3,))

_allreduce = lambda x: _broadcast(sum(x))

print('allreduce(x)=', _allreduce(x))
print('jacobian(x) =\n', jax.jacobian(_allreduce)(x))
print('allreduce^T(y) =', *jax.linear_transpose(_allreduce, x)(y))
print('allreduce(y)   =',  _allreduce(y))
print('jvp(allreduce,x,y) = ', jax.jvp(_allreduce, (x,),(y,))[1])
print('vjp(allreduce,x,y) = ', *jax.vjp(_allreduce,x)[1](y))
```
```
allreduce(x)= [6. 6. 6.]
jacobian(x) =
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
allreduce^T(y) = [18. 18. 18.]
allreduce(y)   = [18. 18. 18.]
jvp(allreduce,x,y) =  [18. 18. 18.]
vjp(allreduce,x,y) =  [18. 18. 18.]
```

**Comment by inailuig** [comment]
I think it should look something like this (without the tokens)
```
def mpi_allreduce_transpose_rule(t, op, comm):

    op_ = unpack_hashable(op)

    if op_ == _MPI.SUM:
        return mpi_allreduce_p.bind(*t, op=op, comm=comm)
    else:
        raise NotImplementedError(
            "The linear transpose of allreduce for {} is not defined".format(op)
        )

ad.deflinear(mpi_allreduce_p, mpi_allreduce_transpose_rule)
```
which also automatically adds the corresponding jvp rule,
however I cannot quite get my head around how to also add the tokens.

**Comment by PhilipVinc** [comment]
1) I still don't get why a matrix of ones? The Allreduce_sum matrix is a block matrix (in my mental picture where you have a block vector of M blocks, each being the data stored on rank/node), as such it can't be a matrix of ones. It's rather a block-matrix of identities? (See the attached picture, curious dog aside.)

In your example I think you are cheated by the broadcast and not considering the effective dimension of the input problem.

1b) The transpose of course is the same matrix.

1c) Notice that the output vector is identical among ranks. So you are justified to take the gradient wrt the local inputs on every rank. This is not valid in general, but for Allreduce it is. Therefore you can assume that on every rank the linear operator is the identity (even though it's not true). 

2) Implementation: tokens are needed to enforce an ordering to MPI operations because XLA might be reordering them causing deadlocks. @dionhaefner knows more about them than me, as it is him who introduced them to solve issues he was having. However, we only care about them in the forward pass, where we execute the MPI operations. 

What we are doing is essentially creating a token (it's just random data) and perform 'mock' operations on it. XLA sees those operations and those are used to enforce an order, but we actually never read them, so the tangeents/cotangents of the tokens are simply propagated with the identity everywhere.

2b) If you have problem with `create_token` try to first write a rule that works if you pass in tokens explicitly, then we can fix it. Maybe stop_gradient does not stop the transposition ?
 
3) Having said that, I don't think that this is the right implementation of the transposition rule. Shouldn't it just do [this](https://github.com/PhilipVinc/mpi4jax/blob/875e60b1737014ecd6885f4c64564705b5ce3c81/mpi4jax/collective_ops/allreduce.py#L167)?



![WhatsApp Image 2020-12-09 at 08 39 55](https://user-images.githubusercontent.com/2407108/101599625-55dbaf80-39fa-11eb-8493-5d4f903c46d2.jpeg)

**Comment by inailuig** [comment]
1. I agree. So far I was assuming for simplicity that we are only working with scalars.
And I also now agree that for us the allreduce_sum is really just a sum (and we can ignore the broadcast to all ranks for the purpose of finding transpose/gradient rules)
2. Seems to be working now when I explicitly pass tokens, see below.
3. I agree. In order to get the correct behaviour when transposing again (and also to use the transpose) we can add a `'identity which is the linear transpose of allreduce_mpi_sum'` primitive (lets call it `mpi_allreduceT_p` for now):

with the following impl and transposition rules:
```
def mpi_allreduceT_impl(x, token, op, comm):
     op_ = unpack_hashable(op)
     if op_ == _MPI.SUM:
         return [x, token]
```
```
def mpi_allreduce_transpose_rule(tan_args, *x_args, op, comm):
     _, token = x_args
     t, _ = tan_args
     if op_ == _MPI.SUM:
        return mpi_allreduceT_p.bind(t, token, op=op, comm=comm)
```
```
def mpi_allreduceT_transpose_rule(tan_args, *x_args, op, comm):
     _, token = x_args
     t, _ = tan_args
     op_ = unpack_hashable(op)
     if op_ == _MPI.SUM:
         return mpi_allreduce_p.bind(t, token, op=op, comm=comm)
```

Then it is possible to implement e.g. distributed MPI matrix vector multiplication which can be transposed arbitrarily many times (with blocks of the columns or blocks of the rows distirbuted across the ranks):

```
test_token = create_token(123)
allreduce_sum = lambda x: mpi4jax.Allreduce(x, op=MPI.SUM, comm=MPI_comm, token= test_token)[0]
allreduce_sumT = lambda y: mpi4jax.AllreduceT(y, op=MPI.SUM, comm=MPI_comm, token= test_token)[0]
```

```
# x is distributed across ranks
# cols of A are distributed across ranks
# result is same on all ranks
def matvec_mpi(A_local, x_local):
    return allreduce_sum(A_local@x_local)
```
```
# y is same on all ranks
# rows of A are distributed across ranks
# result is distributed across ranks
def matvec_transpose_mpi(A_local, y_global):
    return A_local.T @ allreduce_sumT(y_global)  #  allreduce_sumT identity so that it transposes correctly
```

where the `linear_transpose` of `matvec_mpi` does the same as `matvec_transpose_mpi` and vice versa.

See https://github.com/inailuig/mpi4jax/commit/8562397037e46d1f52e683aadf419dd15d1b1704 for the complete implementation including a simple test file which could be transformed into an actual test eventually.
Here it was also crucial to pass the along the token to the transposes, otherwise the tracer would turn it into a normal identity and the second or third transposition would be wrong.

Now the only piece missing is some kind of `stop_transpose` so that we don't have to explicitly pass tokens.
In the case of vjp the parts related to stop_gradient in the jaxpr passed to `ad.backward_pass` are completely removed somewhere in `linearize` if `has_aux= True `is passed. Somehow we have to do the same to the jaxpr in `api.linear_transpose`.

**Comment by PhilipVinc** [comment]
Hmm. Yes, indeed. It is unfortunate that because of this 'trick', we can let go of MPI in the transpose but then we need to add it back in the transposed-transpose...

Moreover, getting rid of the `token` might cause problems: they are there to enforce a well defined order of MPI-execution. The transposed-transpose should inherit the token of the original non-transposed primal, I think.

However, is the transposed-transpose really a thing? Can't we  just implement the transpose rule, with something akin to `stop_transpose` (which is trivial to implement by defining a new function with custom transpose) and then error if someone tries to double transpose that?

**Comment by PhilipVinc** [comment]
PS: would you mind opening a PR so that we can discuss on it and comment it?

**Comment by inailuig** [comment]
If we just need to transpose once we can do this:
```
def _stop_gradient_transpose_rule(primals, tangents):
    return (primals,)

def _create_token_transpose_rule(primals, tangents):
    return (None,)

from jax import ad_util
from jax import lax
ad.primitive_transposes[ad_util.stop_gradient_p] = _stop_gradient_transpose_rule
ad.primitive_transposes[lax.create_token_p] = _create_token_transpose_rule
```
but I think it would be nice if its possible to transpose many times
