### ISSUE TITLE
GPU support

### ISSUE THREAD

**Issue by dionhaefner** [PhilipVinc/mpi4jax#6]
I think in theory it should be possible to communicate data directly from GPU memory. [`mpi4py` seems to support it](https://gist.github.com/lebedov/8514d3456a94a6c73e6d), and we should be able to get a handle to device memory from JAX, e.g. via its `DLPack` support.

**Comment by PhilipVinc** [comment]
Yes, I had investigated this a bit and I'm sure it's possible to support it.
it's on my todo list, but now I don't have access to a GPU.

I'll work on this in October when I pick up a new position and I should have access to a gpu.

**Comment by dionhaefner** [comment]
Sure. If you're eager to start before that, you could also do your testing on Google Colab.

I'd probably give this a stab at some point, but I doubt it will be before next year.

**Comment by dionhaefner** [comment]
This should take 3 main ingredients:

1. Different low-level implementations (Cython or C++) for GPU primitives, because they have a different signature: 
   
   https://github.com/google/jax/blob/b040df20cb3005ec1af472028a3e5dd1b22b17f2/jaxlib/cuda_prng_kernels.cu.cc#L109-L110

2. Different implementation rules to account for layout and workspace:
   
   https://github.com/google/jax/blob/b040df20cb3005ec1af472028a3e5dd1b22b17f2/jaxlib/cuda_prng.py#L38-L59

   (it might be possible to use the same translation rule for CPU and GPU, I haven't figure that out yet)

3. Ensuring that `mpi4py` is built with CUDA support so it can actually read from device memory.


I think it could be valuable to have a workaround right now that does a copy to the host before performing the communication, but I haven't figured out how to do that yet (and have it callable from jitted GPU kernels).

**Comment by PhilipVinc** [comment]
I'm not sure I understand point 1 and 2...

I had given a look at this in the past, and from what I had understood:

 - How the XLA rule should be implemented for GPUs is [detailed here](https://www.tensorflow.org/xla/custom_call#custom-call_on_gpu), and it should simply involve defining a new operation in Cython and registering it for the right XLA backend. We probably have to use the custom-tuple machinery to pass CPU-side parameters (comm, op, stuff like this).

 - Note that we don't really need to write the GPU kernel itself, because we won't have one.

 - The function call itself should still be an `MPI.Allreduce/Send/Whatever` with the same signature. However, as you correctly noted, the MPI library to which `mpi4py` is linked to should be built with MPI support...

**Comment by PhilipVinc** [comment]
Cython, I'd say.
We just need to also link to CUDA somehow and find it's headers in order to get the `cudaStream_t` type. I guess a look at `cupy` internals might help.

**Comment by dionhaefner** [comment]
I think we would ideally not be using the stream at all, right? In that case we could leave that as `void*`.

The GPU Cython wrappers will probably look very similar to the CPU ones, so it's too bad we can't re-use the same functions. Maybe with a thin wrapper that just parses the arguments and calls the CPU implementation.

**Comment by PhilipVinc** [comment]
> I think we would ideally not be using the stream at all, right? In that case we could leave that as void*

Possibly true. 

> The GPU Cython wrappers will probably look very similar to the CPU ones, so it's too bad we can't re-use the same functions. Maybe with a thin wrapper that just parses the arguments and calls the CPU implementation.

we can start by writing new kernels and then see if we can merge them.
As both are CPU-functions that mostly do the same thing, I'd say that you are right: they will mostly be identical
